### ISSUE TITLE
UI is hard to read

### ISSUE THREAD

**Issue by rahgurung** [btholt/complete-intro-to-containers#53]
The UI of lessons are way too wide and it becomes difficult to read it as you have to move your head all the way from left to right to scan the whole text. I propose something like this:
![Screenshot from 2021-11-10 20-39-04](https://user-images.githubusercontent.com/30543444/141139123-884ec9cc-4258-4ca6-ae11-d8db3d0e6be2.png)

I can make a PR.

**Comment by bonface221** [comment]
@rahgurung this is implemented 😎😎😎
